name: imgur
description: A high-level Imgur API Client Library that uses Imgur's v3 API.
version: 1.1.1
homepage: https://github.com/shellbear/imgur.dart
repository: https://github.com/shellbear/imgur.dart

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  test: ^1.6.0
